# -*- coding: utf-8 -*-
# Rich competitor-style sections (challenge / samples / listen) per artist.
# Merged into each artist's PAGES entry by _gen_artists.py at build time.
# Every challenge and listen sentence below is hand-written and structurally
# unique to its artist — no two pages share a sentence frame.

RICH = {
 "the-weeknd": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial moves you from the songs the whole world can already sing to the album cuts hiding behind the neon.",
   "rows": [
    ("🟢", "Easy", "A dozen hits the planet already owns, and each one gives itself away from a single synth glow."),
    ("🟡", "Medium", "Widen the board to twenty-five and the slow-burn follow-ups slide in beside the stadium smashes."),
    ("🟠", "Hard", "At fifty you are working in the dark: a neon filter alone has to tell you which Abel is singing."),
    ("🔴", "Expert", "The same fifty come back, but the clip stops before the vocal does — atmosphere is the only hint."),
    ("💀", "Impossible", "No runway at all now; a tenth of a second of air and the fifty wait for a title."),
   ]},
  "samples": {"eyebrow": "8 of 65", "h2": "Songs in The Weeknd Song Guesser", "intro": "Eight of the 65 tracks in the rotation, from the ragged falsetto of his early tapes to the stadium synths of After Hours.",
   "songs": ["Blinding Lights", "Starboy", "The Hills", "Can't Feel My Face", "Save Your Tears", "Earned It", "Call Out My Name", "Die for You"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🌃", "The synth color comes first", "Blinding Lights opens on a rising arp, Starboy on a low filtered pulse. The shade of the first synth is usually the whole answer."),
    ("🎤", "Read the falsetto's age", "A ragged howl means the early mixtapes, a slick croon the pop years. The first breath tells you which Weeknd is singing."),
    ("🥁", "Feel how the pulse sits", "A slow-burn 808 and a four-on-the-floor kick are two different moods. One clean beat separates Save Your Tears from The Hills."),
   ]},
 },
 "michael-jackson": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "From the songs everyone on Earth can place to the deep cuts only a completist still spins, the dial is the whole range.",
   "rows": [
    ("🟢", "Easy", "You begin with the twelve the world memorized, caught from a beatboxed groove before a word lands."),
    ("🟡", "Medium", "The next stop adds the stadium anthems and the singles that never got the same ceremony."),
    ("🟠", "Hard", "Fifty songs deep, a sharp intake of breath has to stand in for the whole introduction."),
    ("🔴", "Expert", "Shrink the clip until only the gasp survives, and that half-breath has to place the record."),
    ("💀", "Impossible", "The fifty stripped of any warm-up — one tenth of a second, and the groove has not started yet."),
   ]},
  "samples": {"eyebrow": "8 of 70", "h2": "Songs in the Michael Jackson Song Guesser", "intro": "Eight of the 70 tracks in the rotation, spanning the disco-precision of Off the Wall to the harder grooves of the Nineties.",
   "songs": ["Billie Jean", "Thriller", "Beat It", "Smooth Criminal", "Man in the Mirror", "Bad", "Don't Stop 'Til You Get Enough", "Black or White"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🥁", "The rhythm is the ID", "His intros are famously rhythmic — a gated snare, a beatboxed groove, a sharp breath. Each is a fingerprint before a single word."),
    ("🎤", "Hear the stacked vocals", "The layered ad-libs and backing harmonies name the record fast; the arrangement usually beats the melody to the answer."),
    ("🎹", "The bass line is the map", "A locked-in minimal bass belongs to Thriller and Bad, a brighter funk pulse to the earlier disco records."),
   ]},
 },
 "beyonce": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial steps you from the horn-stab anthems toward the album cuts where the arrangement does all the talking.",
   "rows": [
    ("🟢", "Easy", "Start where everyone starts: a dozen records the room can call from the first horn stab."),
    ("🟡", "Medium", "Move up and the singles that charted without becoming the requested one join the rotation."),
    ("🟠", "Hard", "Now the arrangement has to do the naming on its own — the band announces the era before the singer."),
    ("🔴", "Expert", "At expert level the reveal cuts off on the opening snare, before the run has a chance to land."),
    ("💀", "Impossible", "The final tier hands over nothing; a tenth of a second with no signature to lean on."),
   ]},
  "samples": {"eyebrow": "8 of 55", "h2": "Songs in the Beyoncé Song Guesser", "intro": "Eight of the 55 tracks in the rotation, from the horn-heavy strut of Dangerously in Love to the stadium bounce of Renaissance.",
   "songs": ["Crazy in Love", "Single Ladies (Put a Ring on It)", "Halo", "Irreplaceable", "Drunk in Love", "Formation", "Love on Top", "Cuff It"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎺", "The arrangement beats the vocal", "A horn stab means Crazy in Love, a marching-band snare means Formation. The band usually names the song first."),
    ("🎤", "The runs are the shortcut", "Her fastest tell is the vocal, but the production tags each era — a sparse beat is Lemonade, a full band is the early hits."),
    ("🥁", "The pocket picks the room", "A four-on-the-floor kick and a swung soul groove are different sides of the catalog. One clean hit separates Single Ladies from Cuff It."),
   ]},
 },
 "rihanna": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial drops you from the dance-floor smashes to the piano ballads, with everything in between.",
   "rows": [
    ("🟢", "Easy", "The warm-up is a dozen floor-fillers, each one caught from a single steel-drum hit."),
    ("🟡", "Medium", "Add twenty-five more and the hits that landed without defining the era start showing up."),
    ("🟠", "Hard", "At the deep end, one opening hit has to separate the club record from the ballad."),
    ("🔴", "Expert", "Same fifty, but the clip dies just before the kick arrives — no drop to rescue you."),
    ("💀", "Impossible", "Cold open on a tenth of a second; the fifty make no promises and give no warm-up."),
   ]},
  "samples": {"eyebrow": "8 of 68", "h2": "Songs in the Rihanna Song Guesser", "intro": "Eight of the 68 tracks in the rotation, from the dance-floor charge of her club era to the piano ballads.",
   "songs": ["Umbrella", "Diamonds", "We Found Love", "Only Girl (In the World)", "Don't Stop the Music", "Rude Boy", "Stay", "Work"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🥁", "Split the ballads from the bangers", "A steel drum or a four-on-the-floor kick means the club records; a lone piano means the ballads. The first sound names the lane."),
    ("🎤", "The accent is the timestamp", "A Caribbean lilt points to the early hits, a fuller pop belt to the later anthems. The delivery dates the record."),
    ("🎹", "Each single has its own door", "The steel drum of Umbrella, the synth stab of We Found Love, the piano hush of Stay — the lead instrument is the calling card."),
   ]},
 },
 "drake": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep into the mood you are willing to go, from the smash to the late-night cut.",
   "rows": [
    ("🟢", "Easy", "A dozen you can place from the first piano note, the mood already set before he speaks."),
    ("🟡", "Medium", "Twenty-five slide in next — the songs that moved without ever defining the run."),
    ("🟠", "Hard", "Now the opening mood alone has to carry the entire guess across fifty records."),
    ("🔴", "Expert", "You get the sliver of air before the drums knock, and the mood has to finish the job."),
    ("💀", "Impossible", "The board gives you a tenth of a second of atmosphere and it is entirely on you."),
   ]},
  "samples": {"eyebrow": "8 of 69", "h2": "Songs in the Drake Song Guesser", "intro": "Eight of the 69 tracks in the rotation, from the moody piano of his early years to the island bounce of the recent era.",
   "songs": ["God's Plan", "Hotline Bling", "One Dance", "Started from the Bottom", "In My Feelings", "Nice for What", "Passionfruit", "Toosie Slide"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎹", "The mood is the era", "A sparse piano and a slow knock mean the Take Care years; a brighter island bounce means the recent records. The mood dates the song."),
    ("🥁", "The drums tell the room", "A slow, heavy 808 and a four-on-the-floor bounce are two different Drizzy. The pocket names the era."),
    ("🎤", "Catch the opening hook first", "His singles often open on a hook or a sample before a bar. Lock that first sound and the title usually follows."),
   ]},
 },
 "eminem": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how obscure the verse gets — the rules never move.",
   "rows": [
    ("🟢", "Easy", "Twelve the world can name from the first piano loop, the syllables already forming in your head."),
    ("🟡", "Medium", "Widen it to twenty-five and the singles that charted without becoming the signature surface."),
    ("🟠", "Hard", "Fifty tracks where the beat has to name the record on its own, no bars to help."),
    ("🔴", "Expert", "Back to that fifty, but you get only the opening bar before the flow locks in."),
    ("💀", "Impossible", "The bars never arrive — you get one tenth of a second and the fifty stand by."),
   ]},
  "samples": {"eyebrow": "8 of 66", "h2": "Songs in the Eminem Song Guesser", "intro": "Eight of the 66 tracks in the rotation, from the tense piano of his early run to the faster cadences of the later records.",
   "songs": ["Lose Yourself", "Stan", "Without Me", "The Real Slim Shady", "Love the Way You Lie", "Not Afraid", "Rap God", "Mockingbird"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎹", "The piano loop is the door", "A tense piano loop means Lose Yourself, a rainy guitar figure means Stan. The opening melody usually names the record first."),
    ("🥁", "Read the bounce", "A cartoonish, springy beat means the playful singles; a darker, heavier knock means the serious cuts. The pocket is the tell."),
    ("🎤", "The register is the era", "A nasally, sneering delivery means the early records, a clearer, harder flow the recent ones."),
   ]},
 },
 "kanye-west": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial steps you from the era-defining smashes into the deep vault where the sample does all the identifying.",
   "rows": [
    ("🟢", "Easy", "Begin on the dozen everyone knows from a single chipmunked sample, before the drums even land."),
    ("🟡", "Medium", "The middle tier adds the singles that changed the conversation without becoming the hit."),
    ("🟠", "Hard", "Fifty songs now, and the first sample has to carry the whole identification on its own."),
    ("🔴", "Expert", "The same fifty, but the clip stops on the opening sound before the drums lock."),
    ("💀", "Impossible", "Snap the clip before the sample loops and a tenth of a second is all that remains."),
   ]},
  "samples": {"eyebrow": "8 of 61", "h2": "Songs in the Kanye West Song Guesser", "intro": "Eight of the 61 tracks in the rotation, from the soul-chip era to the synth-soaked and gospel-leaning later records.",
   "songs": ["Gold Digger", "Stronger", "Heartless", "Runaway", "All of the Lights", "Jesus Walks", "Flashing Lights", "Power"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎛️", "The sample is a date stamp", "A sped-up soul chip means the College era, a Daft Punk stomp means Graduation. The first sound names the album."),
    ("🥁", "The drums shifted every record", "Boom-bap on the early work, harder electronic kicks later. The pocket is the era."),
    ("🎤", "The first voice tags the period", "A soul loop, a distorted yelp or a choir — whichever opens the track dates it faster than the title."),
   ]},
 },
 "justin-bieber": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep past the radio hits the round digs — the rules stay put.",
   "rows": [
    ("🟢", "Easy", "The opening dozen are songs the room can name from the first strum, the melody already there."),
    ("🟡", "Medium", "Twenty-five join after that — the singles that streamed without ever defining a year."),
    ("🟠", "Hard", "At fifty, a lone strum has to separate the teen era from the recent one."),
    ("🔴", "Expert", "Only the opening shaker survives the cut, and the hook never gets to arrive."),
    ("💀", "Impossible", "No mercy at the bottom: a tenth of a second with no chorus waiting to catch you."),
   ]},
  "samples": {"eyebrow": "8 of 69", "h2": "Songs in the Justin Bieber Song Guesser", "intro": "Eight of the 69 tracks in the rotation, from the glossy R&B strum of his teen years to the trop-house and acoustic ease of the recent era.",
   "songs": ["Baby", "Sorry", "Peaches", "Love Yourself", "What Do You Mean", "Ghost", "Intentions", "Stay"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎛️", "The production is a timeline", "A glossy R&B strum means the early years, a trop-house shaker means Purpose, a laid-back acoustic loop the recent records."),
    ("🥁", "The groove picks the lane", "A bouncy, syncopated beat and a softer pocket are two different chapters. The rhythm names the era."),
    ("🎤", "The delivery brightened", "A boyish, eager tone marks the debut, a warmer, relaxed croon the later hits."),
   ]},
 },
 "linkin-park": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how rare the cut gets — never the rules, never the intensity.",
   "rows": [
    ("🟢", "Easy", "A dozen the crowd can call from the first keyboard loop, no guitar needed yet."),
    ("🟡", "Medium", "Step down one and the singles that carried the album without becoming the anthem appear."),
    ("🟠", "Hard", "Now the blend of electronics and guitar has to do all the naming across fifty tracks."),
    ("🔴", "Expert", "The chug is all you hear before the two voices split — expert cuts it right there."),
    ("💀", "Impossible", "The drop never comes; a tenth of a second and the round is already over."),
   ]},
  "samples": {"eyebrow": "8 of 67", "h2": "Songs in the Linkin Park Song Guesser", "intro": "Eight of the 67 tracks in the rotation, from the atmospheric nu-metal of their debut to the heavier, electronics-laced later records.",
   "songs": ["In the End", "Numb", "One Step Closer", "Crawling", "What I've Done", "New Divide", "Somewhere I Belong", "Breaking the Habit"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎛️", "The balance is the timestamp", "A clean keyboard loop with no guitar means the early nu-metal era, a heavier chug with electronics the later records."),
    ("🥁", "The drop's weight names the song", "A crashing breakdown points to the heavy cuts, a cleaner atmospheric build to the radio singles."),
    ("🎤", "Two voices, one door", "Chester's sung hook and Mike's rapped verse trade places across the catalog. The first voice tags the era."),
   ]},
 },
 "lady-gaga": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial walks you from the dance-floor anthems to the stripped-down ballads and the jazz standards.",
   "rows": [
    ("🟢", "Easy", "Start on a dozen floor-fillers, each one caught from the first synth stomp with the chorus on deck."),
    ("🟡", "Medium", "Twenty-five more, counting the singles that charted without ever becoming the persona-defining one."),
    ("🟠", "Hard", "At fifty the first sound has to tell you which Gaga is standing at the microphone."),
    ("🔴", "Expert", "The same fifty, but the clip ends on the sliver before the beat drops."),
    ("💀", "Impossible", "The stomp never resumes; one tenth of a second and the fifty sit waiting."),
   ]},
  "samples": {"eyebrow": "8 of 69", "h2": "Songs in the Lady Gaga Song Guesser", "intro": "Eight of the 69 tracks in the rotation, from the electro stomp of her debut to the gothic pop and the stripped-down duets.",
   "songs": ["Poker Face", "Bad Romance", "Just Dance", "Shallow", "Rain on Me", "Born This Way", "Telephone", "Paparazzi"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎛️", "Name which Gaga is playing", "A pulsing synth means the dance years, a piano or guitar the ballads, a jazzy swing the standards. The first sound picks the era."),
    ("🎤", "The vocal shape is the tell", "A flat robotic staccato on the club tracks, a raw belt on the ballads. The tone tags the record."),
    ("🥁", "The four-on-the-floor is home", "A steady disco pulse points to the dance singles; a break from it usually means a ballad or a duet."),
   ]},
 },
 "bruno-mars": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep past the party anthems the round reaches — the band stays live either way.",
   "rows": [
    ("🟢", "Easy", "A dozen everyone can place from the first horn blast, the groove already locked in."),
    ("🟡", "Medium", "Add the singles that grooved without ever becoming the wedding standard."),
    ("🟠", "Hard", "Fifty deep, the lead instrument has to name the record with nothing else to go on."),
    ("🔴", "Expert", "Expert hands you the opening lick and then silence; the band never locks in."),
    ("💀", "Impossible", "The horn never returns — a tenth of a second and the fifty give you nothing more."),
   ]},
  "samples": {"eyebrow": "8 of 62", "h2": "Songs in the Bruno Mars Song Guesser", "intro": "Eight of the 62 tracks in the rotation, from the live-band funk to the doo-wop ballads and the 90s R&B throwbacks.",
   "songs": ["Uptown Funk", "Just the Way You Are", "Grenade", "Locked Out of Heaven", "That's What I Like", "24K Magic", "When I Was Your Man", "Treasure"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎺", "The lead instrument is the door", "A horn blast means the funk, a finger-picked guitar the ballads, a slapped bass the throwbacks. The first instrument names the song."),
    ("🥁", "It is a real rhythm section", "A tight, in-the-pocket groove points to the party records, a slower swing to the slow jams."),
    ("🎤", "The falsetto picks the room", "A bright soaring falsetto marks the uptempo hits; a lower, softer croon the ballads."),
   ]},
 },
 "adele": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how rare the ballad gets — every tier still opens on a piano.",
   "rows": [
    ("🟢", "Easy", "The board opens with twelve the room can place from one piano chord, the voice a heartbeat away."),
    ("🟡", "Medium", "Twenty-five follow, the ballads that charted without ever becoming the signature."),
    ("🟠", "Hard", "At fifty, a single chord has to name the record all by itself."),
    ("🔴", "Expert", "The piano sounds and the clip cuts before the vocal lifts; the chord has to carry it."),
    ("💀", "Impossible", "Cut the clip before the chord resolves and all you keep is a tenth of a second."),
   ]},
  "samples": {"eyebrow": "8 of 50", "h2": "Songs in the Adele Song Guesser", "intro": "Eight of the 50 tracks in the rotation, from the stomp of 21 to the hushed piano of 19 and the warmer ease of 30.",
   "songs": ["Rolling in the Deep", "Someone Like You", "Hello", "Set Fire to the Rain", "Skyfall", "Easy on Me", "Send My Love (To Your New Lover)", "When We Were Young"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎹", "The piano voicing is the map", "Each ballad opens on its own chord voicing and tempo, and the albums feel distinct from 19 to 30. The first chord names the record."),
    ("🥁", "The pulse, or its absence", "A stomping handclap beat means Rolling in the Deep; a bare unaccompanied piano means Someone Like You. The rhythm is the tell."),
    ("🎤", "The register deepens", "Her delivery warms across the albums, so the first phrase can tag the era before the chorus lands."),
   ]},
 },
 "ariana-grande": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial moves you past the singalongs toward the album cuts where the production has to carry the guess.",
   "rows": [
    ("🟢", "Easy", "Twelve everyone can name from the first trap-lite hi-hat, the run already half-formed."),
    ("🟡", "Medium", "The pool grows to twenty-five and the singles that shimmered without becoming the signature appear."),
    ("🟠", "Hard", "Fifty tracks where the production has to do the naming on its own, no vocal to help."),
    ("🔴", "Expert", "A shimmer, then nothing — expert stops the clip before the run lands."),
    ("💀", "Impossible", "Slice the clip before the hi-hat skips and a tenth of a second is the entire round."),
   ]},
  "samples": {"eyebrow": "8 of 64", "h2": "Songs in the Ariana Grande Song Guesser", "intro": "Eight of the 64 tracks in the rotation, from the glossy pop-R&B of her early run to the trap-lite bounce of the recent era.",
   "songs": ["thank u, next", "7 rings", "No Tears Left to Cry", "Into You", "positions", "Dangerous Woman", "Break Free", "God is a woman"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎛️", "The production sets the era", "A glossy maximal synth means the early pop, a trap-lite hi-hat means the thank u, next era, a softer R&B pocket the recent singles."),
    ("🎤", "The run or the whisper", "A full melisma means the showcases, a breathy low murmur the intimate cuts. The first phrase tags the mood."),
    ("🥁", "The pocket picks the lane", "A four-on-the-floor pulse and a slower trap bounce are two different records. The beat names the lane."),
   ]},
 },
 "billie-eilish": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep into the dark you are willing to go — from the hit to the hush.",
   "rows": [
    ("🟢", "Easy", "Begin on twelve the room knows from the first sub-bass slide."),
    ("🟡", "Medium", "Twenty-five more, the singles that whispered without ever becoming the one everyone plays."),
    ("🟠", "Hard", "Fifty songs in, the bass has to name the record on its own."),
    ("🔴", "Expert", "The breath is all you get, cut off before the drop, and the fifty wait."),
    ("💀", "Impossible", "The next round is a tenth of a second and the fifty hold their breath too."),
   ]},
  "samples": {"eyebrow": "8 of 58", "h2": "Songs in the Billie Eilish Song Guesser", "intro": "Eight of the 58 tracks in the rotation, from the dreamy early singles to the hushed, bass-heavy later records.",
   "songs": ["bad guy", "Ocean Eyes", "Happier Than Ever", "lovely", "Therefore I Am", "Everything I Wanted", "Bury a Friend", "What Was I Made For?"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🌊", "Listen below the melody", "Her sound lives in the bass and the breath — a slinky sub-bass means bad guy, a soft reverb wash the ballads. The low end is the fingerprint."),
    ("🎤", "The breath is the tell", "A whispered, close-mic delivery marks the quiet cuts; a louder, blown-out chorus the heavier ones."),
    ("🥁", "The beat, or its absence", "A minimal syncopated click points to the groove tracks, silence and reverb to the ballads. The space is the clue."),
   ]},
 },
 "ed-sheeran": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep past the singles the round digs — the loop is always the key.",
   "rows": [
    ("🟢", "Easy", "A dozen everyone can place from the first looped figure, no percussion required."),
    ("🟡", "Medium", "The next twenty-five are the singles that stuck around without ever becoming the signature."),
    ("🟠", "Hard", "At fifty, the loop has to name the record with nothing else on the table."),
    ("🔴", "Expert", "Expert cuts the loop at its first strum, before the percussion ever locks."),
    ("💀", "Impossible", "The loop never returns; one tenth of a second and you are on your own."),
   ]},
  "samples": {"eyebrow": "8 of 70", "h2": "Songs in the Ed Sheeran Song Guesser", "intro": "Eight of the 70 tracks in the rotation, from the loop-pedal acoustic years to the percussive pop of the recent era.",
   "songs": ["Shape of You", "Thinking Out Loud", "Perfect", "Castle on the Hill", "Photograph", "Bad Habits", "Shivers", "Sing"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎸", "The loop is the whole song", "His tracks are built on a single looped figure, and each one is distinct. Lock the rhythm of the loop and the title follows."),
    ("🥁", "The percussion tells the era", "A body-percussion snap and stomp means Shape of You; a full kit means the rock-leaning cuts."),
    ("🎤", "The register picks the lane", "A soft hushed tone marks the ballads; a sharper rhythmic delivery the uptempo singles."),
   ]},
 },
 "coldplay": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial steps you from the stadium anthems to the deep cuts where the first chord does all the work.",
   "rows": [
    ("🟢", "Easy", "Open on twelve the whole stadium knows from the first clean strum."),
    ("🟡", "Medium", "Add the singles that lifted without ever becoming the anthem."),
    ("🟠", "Hard", "Fifty songs deep, the first chord has to name the record by itself."),
    ("🔴", "Expert", "The strings never swell now; expert stops on the opening piano and dares you."),
    ("💀", "Impossible", "Cut the arpeggio short and a tenth of a second is all you get."),
   ]},
  "samples": {"eyebrow": "8 of 68", "h2": "Songs in the Coldplay Song Guesser", "intro": "Eight of the 68 tracks in the rotation, from the reverb-washed early records to the synth-sheened later anthems.",
   "songs": ["Yellow", "Viva la Vida", "Fix You", "The Scientist", "Paradise", "A Sky Full of Stars", "Hymn for the Weekend", "Clocks"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎛️", "Two eras, one band", "A clean piano or acoustic strum means the early records, a synth pad and digital sheen the later ones. The instrumentation is the timestamp."),
    ("🎹", "The piano motif is a fingerprint", "Clocks opens on a cascading arpeggio, The Scientist on a slow chord walk. Each figure is the ID before a word."),
    ("🥁", "The build is the tell", "A slow swelling build points to the ballads, a four-on-the-floor pulse to the dance crossovers."),
   ]},
 },
 "bts": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep past the English smashes the round reaches, toward the layered Korean-era cuts.",
   "rows": [
    ("🟢", "Easy", "A dozen the crowd can name from the first disco sparkle, the chorus already forming."),
    ("🟡", "Medium", "The pool widens to twenty-five and the comebacks that stacked without becoming the global smash appear."),
    ("🟠", "Hard", "At fifty, the first layer on its own has to name the era."),
    ("🔴", "Expert", "The hook never lands; expert keeps only the opening layer and the fifty on deck."),
    ("💀", "Impossible", "Snap the clip before the layers stack and a tenth of a second is the round."),
   ]},
  "samples": {"eyebrow": "8 of 75", "h2": "Songs in the BTS Song Guesser", "intro": "Eight of the 75 tracks in the rotation, from the disco-pop sparkle of the English singles to the layered hip-hop and EDM of the Korean-era cuts.",
   "songs": ["Dynamite", "Butter", "DNA", "Boy With Luv", "Fake Love", "Spring Day", "Permission to Dance", "MIC Drop"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎛️", "The production tags the era", "A disco sparkle means the English hits, a layered hip-hop beat the earlier Korean singles. The first sound is a timestamp."),
    ("🥁", "The layers are the ID", "Their tracks stack many parts at once — a bright synth, a snap, a bass pulse. Lock the loudest layer and the title follows."),
    ("🎤", "The vocal split tags the era", "The rap line and vocal line trade the opening across the catalog — who speaks first names the record."),
   ]},
 },
 "blackpink": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "Thirty-seven tracks, every one a comeback — the dial only changes how far past the title tracks you wander.",
   "rows": [
    ("🟢", "Easy", "Start with a dozen the room can name from the first marching stomp."),
    ("🟡", "Medium", "The next stop adds the comebacks that charted without ever becoming the signature drop."),
    ("🟠", "Hard", "Now the full thirty-seven, and the opening sound has to name the comeback on its own."),
    ("🔴", "Expert", "All thirty-seven return, but the clip dies before the drop shows its shape."),
    ("💀", "Impossible", "The whole catalog with no warm-up — a tenth of a second and no drop to catch you."),
   ]},
  "samples": {"eyebrow": "8 of 37", "h2": "Songs in the BLACKPINK Song Guesser", "intro": "Eight of the 37 tracks in the rotation, from the marching stomp of their debut to the chanted drops of the recent comebacks.",
   "songs": ["DDU-DU DDU-DU", "How You Like That", "Kill This Love", "Pink Venom", "Whistle", "Boombayah", "Lovesick Girls", "Shut Down"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🥁", "The opening stomp is a logo", "Every comeback has its own signature opening — a marching stomp, a chanted drop, a bass thump — so the first half-second is a timestamp."),
    ("🎛️", "The drop's shape names the song", "A hard chanted drop means the fierce singles; a softer melodic lift the slower cuts."),
    ("🎤", "Four voices, one door", "Jennie's rap, Lisa's flow, Jisoo and Rosé's lines trade the opening — the first voice tags the record."),
   ]},
 },
 "gdragon": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "Fifty tracks from a shape-shifting discography — the dial only changes how rare the mutation gets.",
   "rows": [
    ("🟢", "Easy", "Twelve the room can name from the first neon burst, the shape already shifting."),
    ("🟡", "Medium", "The singles that kept mutating never settled into a signature — add those to the board."),
    ("🟠", "Hard", "The full fifty now, and the first beat has to name the era all on its own."),
    ("🔴", "Expert", "The sliver stops before the hook, and all fifty sit behind it."),
    ("💀", "Impossible", "The neon never drops; one tenth of a second and the full catalog waits."),
   ]},
  "samples": {"eyebrow": "8 of 50", "h2": "Songs in the G-DRAGON Song Guesser", "intro": "Eight of the 50 tracks in the rotation, from the neon burst of his early solo years to the self-lacerating later records.",
   "songs": ["Crayon", "Crooked", "Heartbreaker", "That XX", "MichiGO", "Who You", "One of a Kind", "Untitled, 2014"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎛️", "The mutation is the timestamp", "His sound kept changing, so the first beat dates the record — a neon synth burst means the early solo years, a self-lacerating guitar the later ones."),
    ("🥁", "The beat switch is coming", "His tracks often flip their rhythm partway through; the opening pocket still names the era before the switch."),
    ("🎤", "The delivery is the mood", "A snarling, braggadocious tone marks the bangers, a quieter confessional murmur the ballads."),
   ]},
 },
 "david-guetta": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep past the festival singalongs the round goes — the build stays the same weapon.",
   "rows": [
    ("🟢", "Easy", "Begin on twelve the whole festival knows from the first piano lift."),
    ("🟡", "Medium", "Widen it and the singalongs that headlined without ever becoming the era's anthem join in."),
    ("🟠", "Hard", "Fifty songs now, and the build has to name the record by itself."),
    ("🔴", "Expert", "Expert keeps only the opening pad; the drop is a rumor you never hear."),
    ("💀", "Impossible", "The build never starts — a tenth of a second and the fifty stand silent."),
   ]},
  "samples": {"eyebrow": "8 of 64", "h2": "Songs in the David Guetta Song Guesser", "intro": "Eight of the 64 tracks in the rotation, from the vocal-house piano lifts to the big-room and future-rave drops.",
   "songs": ["Titanium", "When Love Takes Over", "Memories", "Without You", "Sexy Bitch", "Hey Mama", "Play Hard", "I'm Good (Blue)"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎛️", "The genre stamp is the door", "A piano lift means the vocal-house era, a big-room synth the festival years, a harder rave stab the recent records."),
    ("🥁", "The build names the era", "His records live on the build and the drop — the length and shape of the build dates the record before the drop lands."),
    ("🎤", "The vocal entry tags it", "A full diva hook means the singalong anthems, a chopped vocal the club tracks."),
   ]},
 },
 "pitbull": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep past the party starters the round reaches — the shout stays the same signal.",
   "rows": [
    ("🟢", "Easy", "A dozen the whole floor knows from the first brass blast, the party already started."),
    ("🟡", "Medium", "The next tier adds the singles that marched without ever becoming the global anthem."),
    ("🟠", "Hard", "At fifty, the first hit has to name the party on its own."),
    ("🔴", "Expert", "The shout is all you get, cut off before the drop, and the fifty stand by."),
    ("💀", "Impossible", "The bass never thumps; one tenth of a second and the fifty are yours to place."),
   ]},
  "samples": {"eyebrow": "8 of 68", "h2": "Songs in the Pitbull Song Guesser", "intro": "Eight of the 68 tracks in the rotation, from the party-starting Latin-pop stomps to the club crossovers and the global smashes.",
   "songs": ["Timber", "Fireball", "Give Me Everything", "Time of Our Lives", "I Know You Want Me (Calle Ocho)", "Rain Over Me", "Feel This Moment", "Don't Stop the Party"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎺", "The horn and the shout", "A brass blast means the party records, a four-on-the-floor kick the club crossovers. The lead sound and the first shout are the calling card."),
    ("🥁", "The stomp is the room", "A stomping, floor-ready beat points to the anthems, a smoother Latin groove to the crossovers."),
    ("🎤", "The chant opens the door", "His tracks often open on a chant or a shout before the verse — that first call tags the record and the mood."),
   ]},
 },
 "kendrick-lamar": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial steps you from the anthems toward the jazz-and-dust deep cuts where the piano does all the talking.",
   "rows": [
    ("🟢", "Easy", "Twelve everyone can place from the first jittery piano, the pocket already swinging."),
    ("🟡", "Medium", "The pool grows to twenty-five and the singles that moved without becoming the protest anthem surface."),
    ("🟠", "Hard", "Now the first sound has to name the record across fifty tracks, no lyric to lean on."),
    ("🔴", "Expert", "The drums never swing now; expert stops the clip on the opening bar alone."),
    ("💀", "Impossible", "Slice the clip before the piano skips and a tenth of a second is all you have."),
   ]},
  "samples": {"eyebrow": "8 of 62", "h2": "Songs in the Kendrick Lamar Song Guesser", "intro": "Eight of the 62 tracks in the rotation, from the jazz-inflected To Pimp a Butterfly era to the harder bounce of the recent records.",
   "songs": ["HUMBLE.", "Alright", "Not Like Us", "DNA.", "Money Trees", "Swimming Pools (Drank)", "All the Stars", "LOVE."]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎛️", "The sonic stamp is the era", "Each album has a signature — a jittery piano means To Pimp a Butterfly, a jazz-funk bounce means DAMN. The first sound names the record."),
    ("🥁", "The swing picks the room", "A loose swung pocket means the jazz records, a hard clipped bounce the recent hits."),
    ("🎤", "The voice shifts pitch", "His delivery bends and changes across the catalog — the first syllable often tells you which record is playing."),
   ]},
 },
 "olivia-rodrigo": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "Fifty tracks, two moods — the dial only changes how deep into the heartbreak the round cuts.",
   "rows": [
    ("🟢", "Easy", "Open with twelve the room can name from the first piano note, the ache already there."),
    ("🟡", "Medium", "The pop-punk sneers land next, the ones that never became the title track."),
    ("🟠", "Hard", "The full fifty now, and the first instrument has to name the mood by itself."),
    ("🔴", "Expert", "The downstroke hits and the clip ends — all fifty, and the sneer never lands."),
    ("💀", "Impossible", "The clip ends before you blink — a tenth of a second and the catalog is already moving."),
   ]},
  "samples": {"eyebrow": "8 of 50", "h2": "Songs in the Olivia Rodrigo Song Guesser", "intro": "Eight of the 50 tracks in the rotation, from the diary-style ballads to the pop-punk sneers of the recent era.",
   "songs": ["drivers license", "good 4 u", "deja vu", "vampire", "traitor", "bad idea right?", "get him back!", "All-American Bitch"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎹", "Two doors, one band", "A lone piano means the ballads, a crunchy guitar downstroke the pop-punk cuts. The first instrument names the lane."),
    ("🥁", "The energy is the mood", "A driving live-band punch means the rock-leaning singles; a sparse slow pulse the piano ballads."),
    ("🎤", "The confessional is close", "Her delivery sits close to the mic on the slow cuts and snaps into a sneer on the loud ones."),
   ]},
 },
 "lana-del-rey": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep into the atmosphere the round reaches — the haze stays the same.",
   "rows": [
    ("🟢", "Easy", "Start on twelve everyone can place from the first string swell, the haze already settling."),
    ("🟡", "Medium", "The slow-burn singles that sighed without a chorus to carry them join the pool."),
    ("🟠", "Hard", "At fifty, the atmosphere has to name the record all by itself."),
    ("🔴", "Expert", "Expert keeps the shimmer and cuts the vocal; the atmosphere has to name it."),
    ("💀", "Impossible", "The strings never return; one tenth of a second and no second listen."),
   ]},
  "samples": {"eyebrow": "8 of 52", "h2": "Songs in the Lana Del Rey Song Guesser", "intro": "Eight of the 52 tracks in the rotation, from the cinematic, nostalgia-soaked singles to the folk-leaning later records.",
   "songs": ["Video Games", "Summertime Sadness", "Born to Die", "Young and Beautiful", "West Coast", "Norman Fucking Rockwell", "Doin' Time", "A&W"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🌊", "The atmosphere is the era", "A string swell means the cinematic singles, a sparse guitar the later folk records, a dreamy synth the early haze."),
    ("🎤", "The register is the tell", "A low languid croon marks the moodier cuts; a clearer, more direct tone the recent records."),
    ("🥁", "The tempo names the lane", "A slow swaying pulse points to the ballads, a steadier trip-hop beat to the rhythmic singles."),
   ]},
 },
 "maroon-5": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep past the radio hits the round reaches — the drift from rock to pop is the whole story.",
   "rows": [
    ("🟢", "Easy", "A dozen the whole room knows from the first funky guitar, the falsetto right behind."),
    ("🟡", "Medium", "The follow-up singles that settled in without ever becoming the smash join the pool."),
    ("🟠", "Hard", "Fifty songs deep, the first instrument has to name the era on its own."),
    ("🔴", "Expert", "The falsetto never arrives; expert stops on the strum and lets the era speak."),
    ("💀", "Impossible", "Cut the clip before the next chorus and a tenth of a second is all that remains."),
   ]},
  "samples": {"eyebrow": "8 of 72", "h2": "Songs in the Maroon 5 Song Guesser", "intro": "Eight of the 72 tracks in the rotation, from the rock-leaning early records to the polished pop of the recent era.",
   "songs": ["Moves Like Jagger", "Sugar", "Girls Like You", "She Will Be Loved", "Payphone", "This Love", "Memories", "One More Night"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎛️", "The drift is the timestamp", "Their sound drifted from rock to radio pop, so the first instrument dates the record — a funky guitar means the early years, a glossy synth the recent hits."),
    ("🎤", "The falsetto is the constant", "Adam's falsetto runs through the catalog — the register and the backing texture tag the era before the chorus."),
    ("🥁", "The groove picks the room", "A four-on-the-floor pulse means the dance crossovers, a looser rock pocket the early records."),
   ]},
 },
 "shakira": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep past the global smashes the round goes — the bilingual range stays the same.",
   "rows": [
    ("🟢", "Easy", "Twelve the whole floor can name from the first trumpet hook, the hips already moving."),
    ("🟡", "Medium", "Then come the records that swayed without a global hook to pin them down."),
    ("🟠", "Hard", "At fifty, the lead instrument has to name the lane with nothing else to go on."),
    ("🔴", "Expert", "The flute sounds and the clip dies before the hip roll; the lane has to answer."),
    ("💀", "Impossible", "The beat never wakes — a tenth of a second and the fifty hold their breath."),
   ]},
  "samples": {"eyebrow": "8 of 67", "h2": "Songs in the Shakira Song Guesser", "intro": "Eight of the 67 tracks in the rotation, from the Latin rock and the trumpet hooks to the Andean flutes and the global pop.",
   "songs": ["Hips Don't Lie", "Whenever, Wherever", "Waka Waka (This Time for Africa)", "La Tortura", "She Wolf", "Try Everything", "Can't Remember to Forget You", "Chantaje"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎺", "The lead instrument is the map", "A trumpet means the big singles, an Andean flute the Latin-rock crossovers, a synth the pop records."),
    ("🥁", "The sway is the era", "A swaying, hip-driven beat points to the Latin records, a four-on-the-floor pulse to the global pop."),
    ("🎤", "Two voices, one catalog", "Her vocal shifts between a full belt and a half-whispered rasp — the first phrase tells you which side is playing."),
   ]},
 },
 "travis-scott": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep into the haze the round cuts — the texture stays the same weapon.",
   "rows": [
    ("🟢", "Easy", "Begin on twelve the whole crowd knows from the first woozy synth."),
    ("🟡", "Medium", "The deeper cuts that loomed never got their own headline moment — they are next."),
    ("🟠", "Hard", "Fifty songs now, and the texture has to name the record all by itself."),
    ("🔴", "Expert", "Expert holds the drone and kills the 808; the haze has to carry the title."),
    ("💀", "Impossible", "The vocal never slurs; one tenth of a second and the fifty stand by."),
   ]},
  "samples": {"eyebrow": "8 of 77", "h2": "Songs in the Travis Scott Song Guesser", "intro": "Eight of the 77 tracks in the rotation, from the mixtape-era haze to the Astroworld textures and the rage-leaning recent records.",
   "songs": ["SICKO MODE", "Goosebumps", "Antidote", "Highest in the Room", "Butterfly Effect", "STARGAZING", "FE!N", "90210"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🌊", "The texture is the fingerprint", "An 808 with a pitched-down vocal means the mixtape era, a woozy synth drone means Astroworld. The first texture names the record."),
    ("🥁", "The 808 tells the era", "A rattling distorted low end points to the rage-leaning cuts, a smoother atmospheric bounce to the earlier records."),
    ("🎤", "The ad-libs open the door", "His auto-tuned ad-libs and low murmurs open many tracks — that first pitched voice usually names the song."),
   ]},
 },
 "sabrina-carpenter": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep past the hooks the round reaches — the wink stays the same signal.",
   "rows": [
    ("🟢", "Easy", "A dozen everyone can place from the first disco bassline, the hook already winking."),
    ("🟡", "Medium", "The wink-first singles that never quite became the anthem slide in."),
    ("🟠", "Hard", "Fifty songs in, the first hook has to name the record with no chorus to catch you."),
    ("🔴", "Expert", "The wink never lands; expert stops before the chorus and the hook sits alone."),
    ("💀", "Impossible", "Snap the clip before the hook lands and a tenth of a second is the whole game."),
   ]},
  "samples": {"eyebrow": "8 of 77", "h2": "Songs in the Sabrina Carpenter Song Guesser", "intro": "Eight of the 77 tracks in the rotation, from the sharp, hook-first recent singles to the earlier pop and the country-kissed cuts.",
   "songs": ["Espresso", "Please Please Please", "Feather", "Nonsense", "Taste", "Skin", "Thumbs", "Because I Liked a Boy"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎛️", "The opening hook is the whole clue", "Her sound is sharp and hook-first, so the opening is the map — a disco bassline means the recent singles, a guitar strum the earlier pop."),
    ("🥁", "The bounce sorts the tempo", "A slinky, dance-ready pulse points to the uptempo singles, a softer pocket to the ballads."),
    ("🎤", "The wink is in the vocal", "A playful, half-spoken delivery marks the bops; a straight, earnest tone the ballads."),
   ]},
 },
 "anuel-aa": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep past the collabs the round goes — the rasp stays the same signal.",
   "rows": [
    ("🟢", "Easy", "Start on twelve the whole floor knows from the first dembow, the rasp right behind."),
    ("🟡", "Medium", "The collabs that landed never became the standout — they join the rotation anyway."),
    ("🟠", "Hard", "At fifty, the first rasp has to name the lane with nothing else on the table."),
    ("🔴", "Expert", "The rasp is all you get, cut before the dembow locks, and the lane waits."),
    ("💀", "Impossible", "Cut the clip before the first bar and a tenth of a second is your whole clue."),
   ]},
  "samples": {"eyebrow": "8 of 51", "h2": "Songs in the Anuel AA Song Guesser", "intro": "Eight of the 51 tracks in the rotation, from the Latin trap and reggaeton collabs to the confessional solo cuts.",
   "songs": ["China", "Ella Quiere Beber", "Secreto", "La Jeepeta", "Sola", "Ayer", "Delincuente", "BEBE"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🥁", "The dembow is the map", "A reggaeton dembow means the club records, a darker trap beat the street cuts. The first beat names the lane before the rasp arrives."),
    ("🎤", "The rasp is the calling card", "His hoarse, half-sung delivery is the constant — the texture of the first phrase tags the record and the mood."),
    ("🎛️", "The beat weight picks the room", "A bouncy bright dembow points to the party collabs, a slow heavy knock to the confessional cuts."),
   ]},
 },
 "don-toliver": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep into the wavy melodic side the round cuts — the falsetto stays the same.",
   "rows": [
    ("🟢", "Easy", "Twelve the whole room can name from the first hazy synth wash, the melody already floating."),
    ("🟡", "Medium", "The wavy singles that drifted without a hook to anchor them appear next."),
    ("🟠", "Hard", "Now the first texture has to name the record across fifty tracks, no vocal to lean on."),
    ("🔴", "Expert", "Expert keeps the falsetto and cuts the bounce; the mood has to answer."),
    ("💀", "Impossible", "The bounce never returns; one tenth of a second and the fifty give nothing."),
   ]},
  "samples": {"eyebrow": "8 of 65", "h2": "Songs in the Don Toliver Song Guesser", "intro": "Eight of the 65 tracks in the rotation, from the wavy early hits to the brighter bounce of the recent records.",
   "songs": ["No Idea", "After Party", "Cardigan", "Lemonade", "Do It Right", "Can't Say", "What You Need", "Private Landing"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🌊", "The first texture is the timestamp", "A hazy synth wash means the early hits, a brighter bounce the recent records. The texture dates the song."),
    ("🎤", "The falsetto is the mood", "A high, wavy falsetto marks the melodic cuts; a lower, more grounded tone the harder ones."),
    ("🥁", "The pocket marks the tempo", "A slow syrupy pocket means the moodier records, a springier beat the uptempo singles."),
   ]},
 },
 "tate-mcrae": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep past the singles the round reaches — the two moods stay the same.",
   "rows": [
    ("🟢", "Easy", "A dozen the whole room can name from the first stomping beat, the step already locked."),
    ("🟡", "Medium", "The dancer-ready singles that stomped but never quite became the one are added."),
    ("🟠", "Hard", "At fifty, the first sound has to name the lane by itself."),
    ("🔴", "Expert", "The step sounds and the clip ends before the chorus; the lane has to speak."),
    ("💀", "Impossible", "Cut the clip before the step hits and a tenth of a second is all that is left."),
   ]},
  "samples": {"eyebrow": "8 of 66", "h2": "Songs in the Tate McRae Song Guesser", "intro": "Eight of the 66 tracks in the rotation, from the dark, dancer-ready singles to the wounded piano ballads.",
   "songs": ["greedy", "You Broke Me First", "Exes", "she's all i wanna be", "10:35", "uh oh", "run for the hills", "i'm so gone"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🥁", "Two lanes, one voice", "A stomping beat means the dance-pop singles, a sparse piano the ballads. The first sound names the lane and the mood."),
    ("🎤", "The wounded tone is the tell", "Her delivery sits low and breathy on the ballads and snaps into a sharper, dancer-ready register on the bops."),
    ("🎛️", "The drop names the room", "A heavy stomping drop points to the club records, a slow piano build to the ballads."),
   ]},
 },
 "playboi-carti": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "Twenty-eight tracks, two eras — the dial only changes how deep into the rage the round cuts.",
   "rows": [
    ("🟢", "Easy", "Start on twelve the whole room can place from the first bouncy 808."),
    ("🟡", "Medium", "The bouncy cuts that never quite became the signature show up."),
    ("🟠", "Hard", "The full twenty-eight now, and the first hit has to name the era all on its own."),
    ("🔴", "Expert", "All twenty-eight return, but the clip dies before the rage kicks in."),
    ("💀", "Impossible", "The whole catalog with no warm-up — a tenth of a second and no drop to save you."),
   ]},
  "samples": {"eyebrow": "8 of 28", "h2": "Songs in the Playboi Carti Song Guesser", "intro": "Eight of the 28 tracks in the rotation, from the minimal bouncy early records to the rage-driven wall of 808s.",
   "songs": ["Magnolia", "Rockstar Made", "Sky", "wokeuplikethis", "Shoota", "@ MEH", "Slay3r", "Stop Breathing"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🥁", "The energy is the era", "His eras are separated by energy — a bouncy minimal beat means the early records, a rage-driven wall of 808s the recent era."),
    ("🎤", "The baby voice is the tell", "His pitched-up, playful delivery marks the early cuts; a harder, rawer tone the recent ones."),
    ("🎛️", "The 808 shape picks the room", "A clean minimal thump points to the early bounce, a distorted overdriven low end to the rage records."),
   ]},
 },
 "bad-bunny": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep into the bend between reggaeton and trap the round cuts.",
   "rows": [
    ("🟢", "Easy", "Twelve the whole floor knows from the first breezy dembow, the hook already riding."),
    ("🟡", "Medium", "The reggaeton singles that bounced without a signature moment appear."),
    ("🟠", "Hard", "At fifty, the dembow alone has to tell you which lane is playing."),
    ("🔴", "Expert", "The synth sounds and the perreo never drops; expert leaves you with a bare lane."),
    ("💀", "Impossible", "The dembow never wakes; one tenth of a second and the fifty wait."),
   ]},
  "samples": {"eyebrow": "8 of 56", "h2": "Songs in the Bad Bunny Song Guesser", "intro": "Eight of the 56 tracks in the rotation, from the breezy reggaeton hits to the darker trap and the dreamy pop crossovers.",
   "songs": ["Tití Me Preguntó", "Me Porto Bonito", "Dakiti", "Yo Perreo Sola", "Safaera", "Ojitos Lindos", "Callaíta", "Moscow Mule"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🥁", "The lane marker is the door", "His sound bends reggaeton, trap and pop — a breezy dembow means the reggaeton hits, a darker synth the trap records."),
    ("🎛️", "The mood picks the era", "A bright playful bounce points to the party records, a slow moody pulse to the deeper cuts."),
    ("🎤", "Two flows, one artist", "A half-sung, melodic flow marks the crossover hits; a harder, clipped rap the trap cuts."),
   ]},
 },
 "katy-perry": {
  "challenge": {"eyebrow": "Turn the dial", "h2": "Choose Your Challenge", "intro": "The dial only changes how deep past the candy anthems the round reaches — the chant stays the same signal.",
   "rows": [
    ("🟢", "Easy", "A dozen everyone can name from the first candy-synth sparkle, the chant already forming."),
    ("🟡", "Medium", "The candy singles that popped without a signature to anchor them come next."),
    ("🟠", "Hard", "Fifty songs deep, the first hook has to name the record with nothing else to go on."),
    ("🔴", "Expert", "The chant is all you hear, cut before the chorus, and the fifty are waiting."),
    ("💀", "Impossible", "Cut the clip right before the chorus and a tenth of a second is all you get."),
   ]},
  "samples": {"eyebrow": "8 of 59", "h2": "Songs in the Katy Perry Song Guesser", "intro": "Eight of the 59 tracks in the rotation, from the candy-colored Teenage Dream era to the stadium chants and the slinky later singles.",
   "songs": ["Firework", "Roar", "Dark Horse", "California Gurls", "Teenage Dream", "Last Friday Night (T.G.I.F.)", "I Kissed a Girl", "Hot n Cold"]},
  "listen": {"eyebrow": "Train the ear", "h2": "What to Listen For",
   "rows": [
    ("🎛️", "The opening hook is the map", "Her hits are hook-first, so the opening is the clue — a stadium chant means Roar, a candy-synth sparkle the Teenage Dream era."),
    ("🥁", "The stomp picks the era", "A stomping four-on-the-floor pulse points to the anthems, a slinkier trap-lite beat to the later singles."),
    ("🎤", "The register splits the moods", "A bright full-throated belt marks the power anthems; a lower, more playful purr the flirtier cuts."),
   ]},
 },
}
